spring:
  application:
    name: backend
  #Jackson
  jackson:
    mapper:
      accept-case-insensitive-values: true
      accept-case-insensitive-enums: true
  # JDBC Pooled Datasource
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SHOW_SQL:false}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
    enabled: true
    url: ${spring.datasource.url}
    user: ${LIQUIBASE_DATASOURCE_USERNAME}
    password: ${LIQUIBASE_DATASOURCE_PASSWORD}

server:
  port: 8080
  ssl:
    key-store-type: ${SSL_KEY_STORE_TYPE}
    key-store: ${SSL_KEY_STORE}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-alias: ${SSL_KEY_ALIAS}

# Log
logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
    reactor:
      netty:
        http:
          client: DEBUG
constant:
  time_hold_sms: 60
  count_number_code: 4
  sms_code_live: 6000

#Jwt
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  issuer: ${spring.application.name}

#SMS Aero
sms-aero:
  enable: false
  url: ${SMS_AERO_URL}
  sign: ${SMS_AERO_SIGN}
  token: ${SMS_AERO_TOKEN}
  login: ${SMS_AERO_LOGIN}

telegram:
  name: mrkvk_test_bot
  token: 5324532057:AAHffyV67hNNkZoPSG2CZFqdHJL5vryAoUo

#Cargoflow
cargoflow:
  url: ${CARGOFLOW_URL}
  username: ${CARGOFLOW_USERNAME}
  password: ${CARGOFLOW_PASSWORD}
  entity:
    endpoint: ${cargoflow.url}${CARGOFLOW_ENTITY_ENDPOINT}
    order: ${CARGOFLOW_ENTITY_ORDER}
    order_history: ${CARGOFLOW_ENTITY_ORDER_HISTORY}
  cuba:
    rest:
      endpoint: ${cargoflow.url}${CARGOFLOW_AUTH_ENDPOINT}
      client:
        id: ${CUBA_REST_CLIENT_ID}
        secret: ${CUBA_REST_CLIENT_SECRET}
#CBRF
cbrf:
  url: ${CBRF_URL}
  scheduler:
    cron: ${CBRF_CRON}
#FEE
customs-fee:
  currency: ${CUSTOMS_FEE_CURRENCY}
  limit-price: ${CUSTOMS_FEE_LIMIT_PRICE}
  fee-price-percent: ${CUSTOMS_FEE_PRICE_PERCENT}
  limit-weight: ${CUSTOMS_FEE_LIMIT_WEIGHT}
  fee-weight-by-kg: ${CUSTOMS_FEE_WEIGHT_BY_KG}
  fixed-our-tax: ${CUSTOMS_FEE_FIXED_OUR_TAX}
  percent-amends: ${CUSTOMS_FEE_PERCENT_AMENDS}
#Robokassa
robokassa:
  url: ${ROBOKASSA_URL}
  merchant_login: ${ROBOKASSA_MERCHANT_LOGIN}
  description: ${ROBOKASSA_DESCRIPTION}
  #none – Без НДС.
  #vat0 – НДС по ставке 0%
  #vat10 – НДС чека по ставке 10%
  #vat110 – НДС чека по расчетной ставке 10/110
  #vat20 – НДС чека по ставке 20%
  #vat120 – НДС чека по расчетной ставке 20/120
  tax: ${ROBOKASSA_TAX}
  algorithm: ${ROBOKASSA_ALGORITHM}
  password_1: ${ROBOKASSA_PASSWORD_1}
  test: ${ROBOKASSA_TEST}
  payment-url: ${ROBOKASSA_PAYMENT_URL}