spring:
  application:
    name: backend
  #Jackson
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  # JDBC Pooled Datasource
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SHOW_SQL:false}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
    enabled: true
    url: ${spring.datasource.url}
    user: ${LIQUIBASE_DATASOURCE_USERNAME}
    password: ${LIQUIBASE_DATASOURCE_PASSWORD}

server:
  port: 8080
  ssl:
    key-store-type: ${SSL_KEY_STORE_TYPE}
    key-store: ${SSL_KEY_STORE}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-alias: ${SSL_KEY_ALIAS}

# Log
logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
    reactor:
      netty:
        http:
          client: DEBUG
constant:
  time_hold_sms: 60
  count_number_code: 4
  sms_code_live: 6000

#Jwt
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  issuer: ${spring.application.name}

#SMS Aero
sms-aero:
  enable: false
  url: ${SMS_AERO_URL}
  sign: ${SMS_AERO_SIGN}
  token: ${SMS_AERO_TOKEN}
  login: ${SMS_AERO_LOGIN}

telegram:
  name: mrkvk_test_bot
  token: 5324532057:AAHffyV67hNNkZoPSG2CZFqdHJL5vryAoUo

#Cargoflow
cargoflow:
  url: ${CARGOFLOW_URL}
  username: ${CARGOFLOW_USERNAME}
  password: ${CARGOFLOW_PASSWORD}
  order:
    endpoint: ${cargoflow.url}${CARGOFLOW_ORDER_ENDPOINT}
  cuba:
    rest:
      endpoint: ${cargoflow.url}${CARGOFLOW_AUTH_ENDPOINT}
      client:
        id: ${CUBA_REST_CLIENT_ID}
        secret: ${CUBA_REST_CLIENT_SECRET}

#CBRF
cbrf:
  url: https://www.cbr.ru/scripts/XML_daily.asp
  scheduler:
    cron: 0 */1 * * * *
#FEE
customs-fee:
  currency: EUR
  limit-price: 20000
  fee-price-percent: 15.0
  limit-weight: 31000
  fee-weight-by-kg: 200
  fixed-our-fee: 500
  percent-amends: 7.0
