{
 "title": "cargoflow metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Топ медленных операций",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, \r\n  histogram_quantile(0.95, \r\n    sum by (le, integration, operation) (rate(integration_operation_duration_seconds_bucket[5m]))\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Общее количество запросов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (integration, operation) (rate(integration_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Процент ошибок",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (integration, operation) (rate(integration_requests_result_total{success=\"false\"}[5m])) \r\n  / \r\n  sum by (integration, operation) (rate(integration_requests_total[5m])) \r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Время выполнения (95 перцентиль)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n  sum by (le, integration, operation) (rate(integration_operation_duration_seconds_bucket[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}